'use strict';
/** Battle v2.3: one rules engine for humans and AI; course state is read-only. */
window.ArcoDuel=(()=>{
 const A=window.ARCO,E=window.ArcoDuelEngine,C=E.config,{escape:esc,icon}=A,$=s=>document.querySelector(s);
 const TOKEN=C.version,KEY='arco.duel.preferences.v230',ALL=Array.from({length:100},(_,i)=>i+1);
 const ROUND_MS=C.answerMs,PREVIEW_MS=C.previewMs,REVEAL_MS=3000,FLOW='auto-reveal-5s-30s-v2';
 let room=null,peerLoad=null,preferredMode='internet',joinCode='',lastError='',selection=new Set(ALL),seen=[];
 const aiProfiles={easy:{name:'入門陪練',accuracy:.55,min:8500,max:14500},normal:{name:'標準對手',accuracy:.75,min:5000,max:11000},hard:{name:'進階樂手',accuracy:.92,min:2400,max:6500}};
 try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(p){selection=new Set(E.normalizeLevels(p.levels));if(p.mode==='local')preferredMode='local';seen=Array.isArray(p.seen)?p.seen.filter(id=>E.Q.has(id)).slice(-1200):[];}}catch(_){}
 const uid=()=>Array.from(crypto.getRandomValues(new Uint8Array(12)),b=>b.toString(16).padStart(2,'0')).join('');
 const randomCode=()=>String(1000+crypto.getRandomValues(new Uint32Array(1))[0]%9000);
 const currentLevel=()=>Math.max(1,Math.min(100,A.getState().lastLevel||1));
 function savePrefs(){try{localStorage.setItem(KEY,JSON.stringify({levels:[...selection],mode:preferredMode,seen:seen.slice(-1200)}));}catch(_){}}
 function markSeen(ids){seen=seen.filter(x=>!ids.includes(x));seen.push(...ids);seen=seen.slice(-1200);savePrefs();}
 function ruleMarkup(){return `<div class="rule"><h3>每局 10 題</h3><p>讀題 ${PREVIEW_MS/1000} 秒，作答 ${ROUND_MS/1000} 秒，公布答案後自動接題。</p></div><div class="rule"><h3>連對與速度加分</h3><p>難度越高、答得越快，得分越多。</p></div><div class="rule"><h3>第 10 題魔王 ×3</h3><p>錯題解析在整局結束後查看。</p></div><details class="battle-rules"><summary>計分規則</summary><div><p>難度基分：1–20 級 100；21–40 級 150；41–60 級 200；61–80 級 250；81–100 級 300。</p><p>作答未滿 3 / 6 / 9 / 12 秒，速度倍率依序為 2 / 1.75 / 1.5 / 1.25；12–30 秒為 1 倍。</p><p>連對 1 / 2–3 / 4–5 / 6 題以上，倍率為 1 / 1.2 / 1.4 / 1.6。錯誤或逾時中斷連對。</p><p>得分 = 基分 × 速度 × 連對；魔王題再乘 3。</p></div></details>`;}

 function scopeMarkup(){const current=currentLevel(),chapter=Math.floor((current-1)/10);return `<fieldset class="battle-scope"><legend>題庫範圍（可多選）</legend><p class="scope-help">所有課程皆可選，不影響闖關進度。</p><div class="scope-shortcuts"><button type="button" class="btn secondary small" data-action="duel-scope-all">全範圍</button><button type="button" class="btn secondary small" data-action="duel-scope-current">目前課程：第 ${current} 級</button><button type="button" class="btn secondary small" data-action="duel-scope-chapter">目前章節：${chapter*10+1}–${chapter*10+10} 級</button><button type="button" class="text-button" data-action="duel-scope-clear">清除選取</button></div><div class="scope-chapters">${A.D.chapters.map((c,i)=>`<label class="scope-chip"><input type="checkbox" data-scope-chapter="${i}" aria-label="選取 ${i*10+1} 到 ${i*10+10} 級"><span><strong>${i*10+1}–${i*10+10} 級</strong><small>${esc(c.title)}</small></span></label>`).join('')}</div><details class="scope-custom"><summary>自訂範圍或個別課程</summary><div class="scope-range"><label>起始級數<input id="scope-from" type="number" min="1" max="100" value="${current}"></label><span aria-hidden="true">至</span><label>結束級數<input id="scope-to" type="number" min="1" max="100" value="${Math.min(current+9,100)}"></label><button type="button" class="btn secondary small" data-action="duel-scope-add">加入此範圍</button></div><label class="scope-search" for="scope-search">找課程<input id="scope-search" type="search" placeholder="輸入級數或課程名稱"></label><div class="scope-levels">${A.D.levels.map(l=>`<label class="scope-level" data-scope-label="${l.id}"><input type="checkbox" data-scope-level="${l.id}"><span><b>${l.id}</b> ${esc(l.title)}</span></label>`).join('')}</div></details><div class="scope-summary" id="scope-summary" aria-live="polite"></div></fieldset>`;}
 function aiLobby(){return `<section class="ai-panel"><div class="ai-panel-heading"><div><span class="subtle-label">一個人也能開局</span><h2 class="icon-heading">${icon('ai')}和 AI 陪練比一場。</h2><p>選好題庫，再選一位對手。</p></div><span class="badge">3,000 題對戰題庫</span></div>${scopeMarkup()}<div class="ai-profiles">${Object.entries(aiProfiles).map(([key,p])=>`<div class="ai-profile"><div class="ai-emblem" aria-hidden="true">${icon(key==='easy'?'music':key==='normal'?'metronome':'layers')}</div><h3>${p.name}</h3><p>${key==='easy'?'留較多思考時間，也會答錯。':key==='normal'?'反應速度與答對傾向居中。':'反應更快，答對傾向較高。'}</p><button class="btn ${key==='normal'?'':'secondary'} small" data-action="duel-ai" data-profile="${key}">挑戰${p.name} ${icon('arrow')}</button></div>`).join('')}</div><p class="connection-note">AI 為離線電腦對手，不使用生成式模型。</p></section>`;}
 function syncScope(){
  document.querySelectorAll('[data-scope-chapter]').forEach(el=>{const start=Number(el.dataset.scopeChapter)*10+1,count=ALL.filter(n=>n>=start&&n<start+10&&selection.has(n)).length;el.checked=count===10;el.indeterminate=count>0&&count<10;el.closest('label').classList.toggle('is-selected',count>0);});
  document.querySelectorAll('[data-scope-level]').forEach(el=>{el.checked=selection.has(Number(el.dataset.scopeLevel));});
  const el=$('#scope-summary');if(el){el.textContent=selection.size?`${E.describe([...selection])} · ${selection.size*30} 題可抽選`:'請至少選一個範圍，再選擇 AI 對手。';el.classList.toggle('is-empty',!selection.size);}
  document.querySelectorAll('[data-action="duel-ai"]').forEach(el=>el.disabled=!selection.size);
 }
 function lobby(){A.setContent(`<div class="page-head"><div><h1>對戰大廳</h1><p>與朋友對戰，或找 AI 陪練。</p></div><span class="badge">3,000 題 · 10 題一局</span></div><div class="duel-intro"><section class="duel-panel"><div class="feature-mark">${icon('users')}</div><h2>約一場樂理對戰</h2><p>一人開房，另一人輸入四位數代碼。</p><div class="battle-full-range">${icon('layers')}<div><strong>全範圍 1–100 級</strong><span>每局由淺入深，五個難度各抽 2 題</span></div></div><div class="form-field"><label for="duel-name">你的暱稱</label><input id="duel-name" maxlength="12" value="${esc(A.getState().name)}" placeholder="例如：今天練琴了嗎" autocomplete="nickname"></div><div class="form-field"><label for="duel-mode">連線方式</label><select id="duel-mode"><option value="internet" ${preferredMode==='internet'?'selected':''}>網際網路連線（PeerJS，需連網）</option><option value="local" ${preferredMode==='local'?'selected':''}>同瀏覽器雙分頁測試（不跨裝置）</option></select></div><button class="btn" data-action="duel-create">建立四位數房間 ${icon('arrow')}</button><hr><div class="form-field"><label for="duel-code">朋友的房間代碼</label><input class="room-code-input" id="duel-code" inputmode="numeric" maxlength="4" pattern="[0-9]{4}" value="${esc(joinCode)}" placeholder="0000" autocomplete="off"></div><button class="btn secondary" data-action="duel-join">加入朋友的房間</button>${lastError?`<div class="connection-state" role="alert">${esc(lastError)}</div>`:''}<details class="connection-help"><summary>連線說明</summary><p class="connection-note">雙方需更新至 v2.3.3。防火牆可能阻擋 PeerJS / WebRTC；本站未提供私人 TURN 中繼或競賽級防作弊。房號不是密碼，請勿使用敏感暱稱。</p></details></section><aside class="duel-side"><div class="duel-side-heading"><img class="duel-side-art" src="${ArcoVisual.art.duel}" alt="木質弦樂樂器與金色譜線" width="450" height="600"><h2><span class="caption-line">觀念要懂，</span><span class="caption-line">答得快也有獎勵。</span></h2></div>${ruleMarkup()}</aside></div>${aiLobby()}`);syncScope();}
 function render(){if(!room){lobby();return;}if(['syncing','preview','playing','reveal'].includes(room.status)){gameView();return;}if(room.status==='result'){resultView();return;}roomView();}
 function createState(host,mode,code,name,levels=ALL){return {id:uid(),host,mode,code,name,levels,otherName:'',otherId:'',status:'connecting',notice:'正在連線，請保持此分頁開啟。',guestReady:false,peer:null,conn:null,channel:null,round:null,index:0,scores:{host:0,guest:0},streaks:{host:0,guest:0},answers:{},answerStatus:{},nextReady:{host:false,guest:false},wins:{host:0,guest:0},matches:0,log:[],lastSeen:Date.now(),matchId:'',rtt:0};}
 function roomView(){const r=room,joined=!!r.otherId,error=r.status==='error';A.setContent(`<div class="quiz-wrap"><div class="quiz-top"><button class="text-button" data-action="duel-leave">${icon('back')}返回對戰大廳</button><span class="badge">${r.mode==='local'?'同瀏覽器雙分頁':'網際網路連線'}</span></div><section class="duel-panel"><h1 style="font-size:28px">${error?'連線已停止':r.status==='connecting'?'正在建立連線':joined?'兩位都到齊了。':'房間已開，等一位朋友。'}</h1><div class="room-code" aria-label="房號 ${r.code.split('').join(' ')}">${esc(r.code)}</div><button class="text-button" data-action="duel-copy">複製房間代碼</button><p>全範圍 1–100 級 · 3,000 題隨機抽選 · 最後魔王題 ×3</p><div class="players"><div class="player"><strong>${esc(r.host?r.name:r.otherName||'房主')}</strong><span>房主${r.host?' · 你':''}</span></div><div class="player"><strong>${esc(r.host?r.otherName||'等待加入':r.name)}</strong><span>${joined?(r.guestReady?'已準備':'尚未準備'):'尚未連線'}${!r.host?' · 你':''}</span></div></div>${error?'<button class="btn secondary" data-action="duel-leave">回大廳重試</button>':r.host?`<button class="btn" data-action="duel-start" ${!joined||!r.guestReady?'disabled':''}>兩人開始挑戰 ${icon('arrow')}</button>`:`<button class="btn" data-action="duel-ready" ${!joined||r.guestReady?'disabled':''}>${r.guestReady?'已準備，等房主開始':'我準備好了'}</button>`}<div class="connection-state" role="status">${esc(r.notice)}</div><p class="connection-note">${r.mode==='local'?'相同瀏覽器另開相同網址的分頁，選擇分頁測試，再輸入房號。這不是跨裝置連線。':'請朋友開啟相同 v2.3.3 或相容新版網站，選網際網路連線並輸入房號。兩人都在線時，房間才會保留。'}</p></section></div>`);}
 function packet(type,data={},target){if(!room)return null;return {app:TOKEN,hash:E.BANK.hash,flow:FLOW,sender:room.id,target:target||room.otherId||'',type,data};}
 function send(type,data={},target){const r=room;if(!r||r.mode==='ai')return;try{const msg=packet(type,data,target);if(r.channel)r.channel.postMessage(msg);else if(r.conn?.open)r.conn.send(msg);}catch(_){fail('訊息無法送達，請回大廳重新連線。');}}
 function cleanupTimers(r){['timer','connectTimer','aiTimer','prepareTimer','autoTimer','autoGuard'].forEach(k=>clearTimeout(r[k]));['tick','heartbeat','autoTick'].forEach(k=>clearInterval(r[k]));}
 function fail(message){const r=room;if(!r)return;cleanupTimers(r);r.status='error';r.notice=message;try{r.channel?.close();r.conn?.close();r.peer?.destroy();}catch(_){}A.stopAudio();render();}
 function heartbeat(){const r=room;if(!r)return;clearInterval(r.heartbeat);r.lastSeen=Date.now();r.heartbeat=setInterval(()=>{if(room!==r)return;if(r.otherId){if(Date.now()-r.lastSeen>16000){fail('超過 16 秒未收到對方回應，本局已停止，請重新開房。');return;}send('ping',{at:Date.now()});}},3000);}
 function readForm(){preferredMode=$('#duel-mode')?.value||preferredMode;joinCode=($('#duel-code')?.value||'').trim();const name=($('#duel-name')?.value||A.getState().name||'練習中的樂手').trim().slice(0,12)||'練習中的樂手';A.setName(name);savePrefs();return {name,mode:preferredMode};}
 async function start(host){const cfg=readForm();lastError='';if(!host&&!/^\d{4}$/.test(joinCode)){lastError='房間代碼需要 4 個數字。';lobby();$('#duel-code').focus();return;}if(cfg.mode==='local'&&!window.BroadcastChannel){lastError='瀏覽器不支援分頁同步，請使用新版瀏覽器。';lobby();return;}leave(false);room=createState(host,cfg.mode,host?randomCode():joinCode,cfg.name);render();if(cfg.mode==='local')startLocal();else await startInternet();}
 function startLocal(){const r=room;try{r.channel=new BroadcastChannel('arco-music-v230-room-'+r.code);r.channel.onmessage=e=>receive(e.data);}catch(_){fail('無法開啟分頁通道；請讓兩頁使用完全相同的 http/https 網址。');return;}if(r.host){send('probe',{},'*');r.connectTimer=setTimeout(()=>{if(room!==r||r.status==='error')return;r.status='waiting';r.notice='房間開啟中，等待另一個分頁加入。';heartbeat();render();},350);}else{send('hello',{name:r.name},'*');r.connectTimer=setTimeout(()=>{if(room===r&&!r.otherId)fail('找不到房間，請確認相同網址、瀏覽器、版本與分頁測試模式。');},6500);heartbeat();}}
 async function loadPeer(){if(window.Peer)return window.Peer;if(peerLoad)return peerLoad;peerLoad=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://unpkg.com/peerjs@1.5.4/dist/peerjs.min.js';s.async=true;const timer=setTimeout(()=>{s.remove();peerLoad=null;reject(Error('timeout'));},10000);s.onload=()=>{clearTimeout(timer);if(window.Peer)resolve(window.Peer);else{peerLoad=null;reject(Error('peer unavailable'));}};s.onerror=()=>{clearTimeout(timer);peerLoad=null;s.remove();reject(Error('load'));};document.head.appendChild(s);});return peerLoad;}
 async function startInternet(attempt=0){const r=room;try{const Peer=await loadPeer();if(room!==r)return;const p=new Peer(r.host?'arco-music-v230-'+r.code:undefined,{debug:0});r.peer=p;r.connectTimer=setTimeout(()=>{if(room===r&&r.status==='connecting')fail('連線逾時，請檢查房號與網路。');},15000);p.on('open',()=>{if(room!==r)return;if(r.host){clearTimeout(r.connectTimer);r.status='waiting';r.notice='已連上訊號服務，請分享四位數房號。';render();}else wire(p.connect('arco-music-v230-'+r.code,{reliable:true,serialization:'json'}),false);heartbeat();});p.on('connection',c=>{if(room!==r){c.close();return;}if(r.conn){c.on('open',()=>{c.send(packet('busy',{},'*'));setTimeout(()=>c.close(),250);});return;}wire(c,true);});p.on('error',err=>{if(room!==r)return;if(err.type==='unavailable-id'&&r.host&&attempt<3){clearTimeout(r.connectTimer);r.peer=null;p.destroy();r.code=randomCode();startInternet(attempt+1);return;}fail(err.type==='peer-unavailable'?'找不到房間，請確認相同版本與房號，且房主仍在線。':'無法完成網路連線，請重試或使用同瀏覽器分頁測試。');});p.on('disconnected',()=>{if(room===r&&r.peer===p&&r.status!=='error')fail('訊號服務連線已中斷，請重新開房。');});}catch(_){if(room===r)fail('無法載入網路連線元件。單人功能正常，可使用 AI 或分頁測試。');}}
 function wire(conn,incoming){const r=room;if(!r)return;r.conn=conn;conn.on('open',()=>{if(room===r&&!incoming)send('hello',{name:r.name},'*');});conn.on('data',receive);conn.on('close',()=>{if(room===r&&r.status!=='error')fail('對方已離開或連線中斷，本局已停止。');});conn.on('error',()=>{if(room===r)fail('資料連線發生錯誤，請重新加入房間。');});}
 const validOrder=order=>Array.isArray(order)&&order.length===4&&order.every(Number.isInteger)&&[...order].sort().join('')==='0123';
 const validScores=s=>({host:Math.max(0,Math.min(999999,Number(s?.host)||0)),guest:Math.max(0,Math.min(999999,Number(s?.guest)||0))});
 function sameRound(d){return room&&d.matchId===room.matchId&&d.roundId===room.round?.roundId&&d.index===room.index;}
 function receive(msg){
  const r=room;if(!r||r.status==='error'||!msg||typeof msg!=='object'||msg.app!==TOKEN||msg.sender===r.id||typeof msg.sender!=='string'||msg.sender.length>100)return;
  if(msg.target&&msg.target!=='*'&&msg.target!==r.id)return;const d=msg.data&&typeof msg.data==='object'?msg.data:{};
  if(msg.type==='probe'&&r.host&&r.status!=='connecting'){send('occupied',{},msg.sender);return;}
  if(msg.type==='occupied'&&r.host&&r.status==='connecting'){fail('此房號已使用，請重新建立。');return;}
  if(msg.type==='busy'){fail('房間已有兩位玩家，請另開房間。');return;}
  if(msg.type==='mismatch'){fail('對戰版本不同，請兩人重新載入 v2.3.3 或相容新版，再開房。');return;}
  if(msg.type==='hello'&&r.host){if(r.otherId&&r.otherId!==msg.sender){send('busy',{},msg.sender);return;}if(msg.hash!==E.BANK.hash||msg.flow!==FLOW){send('mismatch',{},msg.sender);fail('對方的對戰流程版本不同，請兩人更新網頁後重新開房。');return;}if(!['waiting','connecting'].includes(r.status))return;r.otherId=msg.sender;r.otherName=String(d.name||'另一位樂手').slice(0,12);r.lastSeen=Date.now();r.status='waiting';r.notice='朋友已加入，等對方按準備。';send('welcome',{name:r.name});render();return;}
  if(msg.type==='welcome'&&!r.host&&!r.otherId){if(msg.hash!==E.BANK.hash||msg.flow!==FLOW){fail('對戰版本不同，請兩人更新網頁後重新開房。');return;}r.otherId=msg.sender;r.otherName=String(d.name||'房主').slice(0,12);r.status='waiting';r.notice='已加入。準備好後按「我準備好了」。';clearTimeout(r.connectTimer);r.lastSeen=Date.now();render();return;}
  if(msg.sender!==r.otherId)return;if(msg.hash!==E.BANK.hash){fail('對方題庫版本已改變，請重新連線。');return;}r.lastSeen=Date.now();
  if(msg.type==='ping'){send('pong',{at:d.at});return;}
  if(msg.type==='pong'){const sample=Date.now()-Number(d.at);if(sample>=0&&sample<5000)r.rtt=sample;return;}
  if(msg.type==='leave'){fail('對方已離開房間，本局已停止。');return;}
  if(msg.type==='ready'&&r.host&&r.status==='waiting'){r.guestReady=true;r.notice='兩人已準備，可開始。';send('ready-confirm');render();return;}
  if(msg.type==='ready-confirm'&&!r.host&&r.status==='waiting'){r.guestReady=true;r.notice='已準備，等房主開始。';render();return;}
  if(msg.type==='prepare'&&!r.host){
   const q=E.Q.get(d.qid);if(!q||!Number.isInteger(d.index)||d.index<0||d.index>9||!validOrder(d.order)||typeof d.matchId!=='string'||typeof d.roundId!=='string')return;
   if(d.index===0){if(r.status!=='waiting')return;r.reviewFilter='wrong';}else if(r.status!=='reveal'||d.matchId!==r.matchId||d.index!==r.index+1)return;
   clearAuto(r);clearInterval(r.tick);r.matchId=d.matchId;r.index=d.index;r.round={...d,boss:d.index===9};r.scores=validScores(d.scores);r.streaks=validScores(d.streaks);r.answers={};r.answerStatus={};r.nextReady={host:false,guest:false};r.status='syncing';r.readySentAt=Date.now();r.scheduled=false;r.sentTimeout=false;markSeen([q.id]);A.stopAudio();render();send('round-ready',{index:r.index,matchId:r.matchId,roundId:d.roundId,sentAt:r.readySentAt});r.prepareTimer=setTimeout(()=>{if(room===r&&r.status==='syncing'&&!r.scheduled)fail('題目同步逾時，請重新開房。');},10000);return;
  }
  if(msg.type==='round-ready'&&r.host&&r.status==='syncing'&&sameRound(d)&&!r.scheduled){clearTimeout(r.prepareTimer);r.rtt=Math.max(0,Date.now()-r.preparedAt);scheduleRound(d.sentAt);return;}
  if(msg.type==='schedule'&&!r.host&&r.status==='syncing'&&sameRound(d)&&!r.scheduled){
   if(!Number.isFinite(d.hostSent)||!Number.isFinite(d.previewAt)||d.previewAt<d.hostSent||d.previewAt-d.hostSent>3000)return;
   if(d.echo!==r.readySentAt||d.answerAt-d.previewAt!==PREVIEW_MS||d.endAt-d.answerAt!==ROUND_MS)return;
   const received=Date.now(),trip=Math.max(0,received-r.readySentAt);r.clockOffset=d.hostSent-(r.readySentAt+received)/2;r.rtt=trip;installSchedule(d,r.clockOffset);return;
  }
  if(msg.type==='answer'&&r.host&&sameRound(d)&&['playing','preview'].includes(r.status)){takeAnswer('guest',d.choice,{reported:d.elapsedMs});return;}
  if(msg.type==='answer-status'&&!r.host&&sameRound(d)&&['playing','preview'].includes(r.status)){r.answerStatus={host:!!d.host,guest:!!d.guest};const node=$('#duel-wait-status');if(node)node.textContent=waitText();return;}
  if(msg.type==='reveal'&&!r.host&&sameRound(d)&&['playing','preview'].includes(r.status)){clearTimeout(r.timer);clearInterval(r.tick);r.status='reveal';r.answers=cleanAnswers(d.answers);r.scores=validScores(d.scores);r.streaks=validScores(d.streaks);r.nextReady={host:false,guest:false};r.log.push({qid:r.round.qid,boss:r.index===9,answers:structuredClone(r.answers)});A.stopAudio();startAutoReveal();render();ArcoAudio.effect(r.answers.guest?.correct);return;}
  if(msg.type==='next'&&r.host&&r.status==='reveal'&&sameRound(d)){r.nextReady.guest=true;maybeAdvance();return;}
  if(msg.type==='result'&&!r.host&&r.status==='reveal'&&r.index===9&&d.matchId===r.matchId){clearAuto(r);r.status='result';r.scores=validScores(d.scores);r.wins=validScores(d.wins);r.matches=Math.max(1,Math.min(999,Number(d.matches)||1));render();return;}
  if(msg.type==='rematch'&&!r.host&&r.status==='result'){r.status='waiting';r.guestReady=false;r.notice='房主邀請再來一局，請按準備。';r.round=null;r.log=[];render();}
 }function startAi(profile){if(!selection.size){A.notify('至少選一個題庫範圍。');return;}const cfg=readForm();leave(false);room=createState(true,'ai','AI',cfg.name,E.normalizeLevels([...selection]));Object.assign(room,{status:'waiting',otherId:'local-ai',otherName:(aiProfiles[profile]||aiProfiles.normal).name,guestReady:true,aiProfile:profile,aiConfig:aiProfiles[profile]||aiProfiles.normal});hostStart();}
 function hostStart(){const r=room;if(!r?.host||!r.otherId||!r.guestReady||r.status!=='waiting')return;
  try{r.prepared=E.sample(r.mode==='ai'?r.levels:ALL,seen).map(q=>q.id);}catch(e){A.notify(e.message);return;}
  r.matchId=uid();r.reviewFilter='wrong';r.index=0;r.scores={host:0,guest:0};r.streaks={host:0,guest:0};r.log=[];markSeen(r.prepared);beginRound();
 }
 function beginRound(){const r=room;if(!r?.host)return;clearAuto(r);clearTimeout(r.aiTimer);clearTimeout(r.timer);clearInterval(r.tick);
  const q=E.Q.get(r.prepared[r.index]);r.round={qid:q.id,index:r.index,order:A.shuffle([0,1,2,3]),roundId:uid(),matchId:r.matchId,boss:r.index===9,scores:{...r.scores},streaks:{...r.streaks}};
  r.status='syncing';r.answers={};r.answerStatus={};r.nextReady={host:false,guest:false};r.scheduled=false;r.sentTimeout=false;r.aiPlanned=null;r.preparedAt=Date.now();A.stopAudio();render();
  if(r.mode==='ai'){scheduleRound();return;}send('prepare',r.round);r.prepareTimer=setTimeout(()=>{if(room===r&&r.status==='syncing'&&!r.scheduled)fail('對方尚未載入題目，同步逾時，請重新開房。');},10000);
 }
 function roundRef(){const r=room;return {matchId:r.matchId,roundId:r.round.roundId,index:r.index};}
 function scheduleRound(echo){const r=room;if(!r?.host||r.scheduled)return;const hostSent=Date.now(),lead=r.mode==='ai'?200:Math.min(1800,Math.max(600,r.rtt*3));
  const d={...roundRef(),hostSent,echo,previewAt:hostSent+lead,answerAt:hostSent+lead+PREVIEW_MS,endAt:hostSent+lead+PREVIEW_MS+ROUND_MS};send('schedule',d);installSchedule(d,0);
 }
 function installSchedule(d,offset){const r=room;clearTimeout(r.prepareTimer);r.scheduled=true;const now=performance.now(),hostNow=Date.now()+offset;
  r.previewMono=now+(d.previewAt-hostNow);r.answerMono=now+(d.answerAt-hostNow);r.deadlineMono=r.answerMono+ROUND_MS;
  r.localDeadline=Date.now()+(r.deadlineMono-now);r.startedAt=Date.now()+(r.answerMono-now);
  clearInterval(r.tick);r.tick=setInterval(pulse,40);pulse();
 }
 function openAnswers(){const r=room;if(!r||r.status==='playing')return;r.status='playing';render();if(r.mode==='ai')scheduleAi();}
 function pulse(){const r=room;if(!r||!r.scheduled||!['syncing','preview','playing'].includes(r.status))return;const now=performance.now();
  if(r.status==='syncing'&&now>=r.previewMono){r.status='preview';render();}
  if(r.status==='preview'&&now>=r.answerMono)openAnswers();
  const seconds=$('#duel-seconds'),label=$('#duel-clock-label'),meter=$('#duel-timer-fill');
  if(seconds){const remaining=r.status==='playing'?r.deadlineMono-now:r.status==='preview'?r.answerMono-now:0;seconds.textContent=r.status==='syncing'?'—':String(Math.max(0,Math.ceil(remaining/1000)));if(label)label.textContent=r.status==='preview'?'讀題':r.status==='syncing'?'同步':'作答';if(meter){const fraction=r.status==='playing'?(r.deadlineMono-now)/ROUND_MS:r.status==='preview'?(r.answerMono-now)/PREVIEW_MS:0;meter.style.transform=`scaleX(${Math.max(0,Math.min(1,fraction))})`;meter.classList.toggle('urgent',r.status==='playing'&&remaining<=3000);}}
  if(r.status==='playing'&&now>=r.deadlineMono){
   if(r.host){if(!r.answers.host)takeAnswer('host',null,{timed:true});if(room!==r||r.status!=='playing')return;
    if(r.mode==='ai'){if(!r.answers.guest)takeAnswer('guest',null,{timed:true});}
    else if(!r.graceScheduled){r.graceScheduled=true;r.timer=setTimeout(()=>{if(room===r&&r.status==='playing'&&!r.answers.guest)takeAnswer('guest',null,{timed:true});},250);}
   }else if(!r.answers.guest&&!r.sentTimeout){r.sentTimeout=true;r.answers.guest={choice:null};send('answer',{...roundRef(),choice:null,elapsedMs:ROUND_MS});render();}
  }
 }
 function scheduleAi(){const r=room;if(!r||r.mode!=='ai')return;clearTimeout(r.aiTimer);const cfg=r.aiConfig,q=E.Q.get(r.round.qid);const choice=Math.random()<cfg.accuracy?q.correct:A.shuffle([0,1,2,3].filter(i=>i!==q.correct))[0];const delay=cfg.min+Math.random()*(cfg.max-cfg.min),roundId=r.round.roundId;r.aiPlanned={choice,delay};r.aiTimer=setTimeout(()=>{if(room===r&&r.round.roundId===roundId&&r.status==='playing')takeAnswer('guest',choice);},Math.max(0,r.answerMono+delay-performance.now()));}
 function takeAnswer(who,choice,{timed=false,reported}={}){
  const r=room;if(!r?.host||!['host','guest'].includes(who)||r.answers[who])return;
  const observed=performance.now()-r.answerMono;if(observed<0)return;if(r.status==='preview')openAnswers();if(r.status!=='playing')return;
  if(!timed&&choice!==null&&(!Number.isInteger(choice)||choice<0||choice>3))return;
  let elapsed=observed;
  if(who==='guest'&&r.mode!=='ai'&&!timed){
   if(!Number.isFinite(reported)||reported<0||reported>ROUND_MS)return;
   // Client reports elapsed time, never points. Bound the report by host receipt time.
   const allowance=Math.min(250,Math.max(0,r.rtt/2));elapsed=Math.max(reported,observed-allowance);
   if(observed>ROUND_MS+250)elapsed=ROUND_MS;
  }
  if(timed||elapsed>=ROUND_MS){choice=null;elapsed=ROUND_MS;}
  const q=E.Q.get(r.round.qid),result=E.score({correct:choice!==null&&choice===q.correct,tier:q.tier,elapsedMs:elapsed,streak:r.streaks[who],boss:r.index===9});
  r.streaks[who]=result.streak;r.answers[who]={choice,...result};r.scores[who]+=result.points;r.answerStatus={host:!!r.answers.host,guest:!!r.answers.guest};send('answer-status',{...roundRef(),...r.answerStatus});
  if(r.answers.host&&r.answers.guest)reveal();else if(who==='host')render();else{const node=$('#duel-wait-status');if(node)node.textContent=waitText();}
 }
 function cleanAnswers(input){const q=E.Q.get(room.round.qid),out={};for(const who of ['host','guest']){const a=input?.[who];const choice=Number.isInteger(a?.choice)&&a.choice>=0&&a.choice<4?a.choice:null;const result=E.score({correct:choice!==null&&choice===q.correct,tier:q.tier,elapsedMs:Number(a?.elapsedMs),streak:room.round.streaks?.[who]||0,boss:room.index===9});out[who]={choice,...result};}return out;}
 function clearAuto(r){for(const k of ['autoTimer','autoGuard']){clearTimeout(r[k]);r[k]=null;}clearInterval(r.autoTick);r.autoTick=null;}
 function updateAutoReveal(){const r=room;if(!r||r.status!=='reveal')return;const el=$('#duel-auto-status');if(!el)return;const sec=Math.max(0,Math.ceil((r.autoAt-performance.now())/1000));el.textContent=sec?`${sec} 秒後自動${r.index===9?'查看結果':'開始下一題'}`:'正在同步下一題';}
 function startAutoReveal(){
  const r=room;if(!r||r.status!=='reveal')return;clearAuto(r);const roundId=r.round.roundId;
  r.nextReady={host:false,guest:r.mode==='ai'};r.autoAt=performance.now()+REVEAL_MS;
  r.autoTick=setInterval(updateAutoReveal,100);
  r.autoTimer=setTimeout(()=>{if(room!==r||r.status!=='reveal'||r.round.roundId!==roundId)return;const me=r.host?'host':'guest';r.nextReady[me]=true;updateAutoReveal();if(r.host)maybeAdvance();else send('next',roundRef());},REVEAL_MS);
  r.autoGuard=setTimeout(()=>{if(room===r&&r.status==='reveal'&&r.round.roundId===roundId)fail('自動接題同步逾時，請確認雙方網頁仍開啟並使用相同新版。');},15000);
 }
 function reveal(){const r=room;if(!r||r.status!=='playing')return;clearTimeout(r.timer);clearTimeout(r.aiTimer);clearInterval(r.tick);r.graceScheduled=false;r.status='reveal';r.log.push({qid:r.round.qid,boss:r.index===9,answers:structuredClone(r.answers)});send('reveal',{...roundRef(),answers:r.answers,scores:r.scores,streaks:r.streaks});A.stopAudio();startAutoReveal();render();ArcoAudio.effect(r.answers[r.host?'host':'guest']?.correct);}
 function maybeAdvance(){const r=room;if(!r?.host||r.status!=='reveal'||!r.nextReady.host||!r.nextReady.guest)return;clearAuto(r);if(r.index===9){r.status='result';r.matches++;if(r.scores.host>r.scores.guest)r.wins.host++;else if(r.scores.guest>r.scores.host)r.wins.guest++;send('result',{matchId:r.matchId,scores:r.scores,wins:r.wins,matches:r.matches});render();}else{r.index++;beginRound();}}
 function waitText(){const r=room,me=r.host?'host':'guest',other=r.host?'guest':'host';if(r.answers[me]||r.answerStatus[me])return '已作答，等待對方。';if(r.answers[other]||r.answerStatus[other])return '對方已作答';return '選擇答案，或按鍵盤 1–4。';}
 function breakdown(a){if(!a?.correct)return '0 分 · 連對歸零';return `${a.base} 基分 × ${a.speed} 速度 × ${a.combo} 連對${a.boss===3?' × 3 魔王':''} ＝ ${a.points} 分`;}
 function scoreBoard(){const r=room,before=['syncing','preview','playing'].includes(r.status),scores=before?r.round.scores:r.scores,streaks=before?r.round.streaks:r.streaks;return `<div class="duel-scoreboard">${['host','guest'].map(who=>{const mine=who===(r.host?'host':'guest'),name=who==='host'?(r.host?r.name:r.otherName):(r.host?r.otherName:r.name);return `<div><div class="player-name">${esc(name)}${mine?' · 你':''}</div><div class="points">${scores?.[who]||0}<small> 分</small></div><span class="streak-tag">連對 ${streaks?.[who]||0} 題</span></div>`;}).join('')}</div>`;}
 function gameView(){const r=room,q=E.Q.get(r.round.qid),me=r.host?'host':'guest',other=r.host?'guest':'host',mine=r.answers[me],revealed=r.status==='reveal',visible=['playing','reveal'].includes(r.status),syncing=r.status==='syncing';
  const demo=q.audio?A.audioCard({...q.audio,label:'試聽不暫停計時'},'duel',q.id):'';
  A.setContent(`<div class="quiz-wrap battle-game"><div class="quiz-top"><button class="text-button" data-action="duel-leave">${icon('back')}${r.mode==='ai'?'離開對戰':'離開房間'}</button><div class="quiz-meta">${r.mode==='ai'?'AI 陪練 · '+esc(r.otherName):r.mode==='local'?'分頁測試 · 房號 '+r.code:'雙人對戰 · 房號 '+r.code}<br>${r.mode==='ai'?esc(E.describe(r.levels)):'全範圍 1–100 級'}</div></div>${scoreBoard()}<article class="quiz-card ${r.index===9?'boss-card':''}"><div class="question-label"><span>第 ${r.index+1} 題 / 10</span>${r.index===9?`<span class="boss-badge">${icon('trophy')}魔王題 ×3</span>`:''}<span class="duel-clock"><span id="duel-clock-label">${revealed?'完成':syncing?'同步':r.status==='preview'?'讀題':'作答'}</span>${icon('clock')}<b id="duel-seconds">${revealed?'—':r.status==='preview'?String(PREVIEW_MS/1000):syncing?'—':String(ROUND_MS/1000)}</b>${revealed?'':'秒'}</span></div><div class="battle-time-track" aria-hidden="true"><span id="duel-timer-fill" style="transform:scaleX(${revealed?0:1})"></span></div><div class="battle-question-meta"><span>${esc(C.tierNames[q.tier-1])}</span><span>第 ${q.level} 級 · ${esc(A.lesson(q.level).title)}</span></div>${syncing?'<div class="battle-sync" role="status">正在同步題目，兩邊到齊再開始。</div>':`<h1 tabindex="-1" id="battle-question">${esc(q.prompt)}</h1>${q.staff?A.staffView(q.staff):''}${demo}`}${visible?`<div class="options" role="group" aria-label="答案選項">${r.round.order.map((choice,i)=>`<button class="option ${revealed?(choice===q.correct?'correct':mine?.choice===choice?'wrong':'dim'):mine?.choice===choice?'current':''}" type="button" aria-pressed="${mine?.choice===choice}" data-action="duel-answer" data-choice="${choice}" data-round="${r.round.roundId}" ${mine||revealed?'disabled':''}><span class="letter">${'ABCD'[i]}</span><span class="option-copy">${esc(q.options[choice])}</span>${revealed&&choice===q.correct?icon('check'):revealed&&mine?.choice===choice?icon('close'):''}</button>`).join('')}</div>`:!syncing?'<div class="battle-preview" role="status">選項即將出現</div>':''}${revealed?`<div class="answer-feedback round-reveal ${mine?.correct?'':'bad'}" role="status"><div class="round-result-line"><strong>${mine?.correct?'答對了':mine?.choice===null?'這題未作答':'這題未答對'}</strong></div><p>正確答案：<strong>${esc(q.options[q.correct])}</strong></p></div><div class="auto-round-footer"><div class="auto-round-progress" aria-hidden="true"><span></span></div><strong id="duel-auto-status">3 秒後自動${r.index===9?'查看結果':'開始下一題'}</strong></div>`:visible?`<div class="connection-state" id="duel-wait-status" role="status">${waitText()}</div>`:''}</article></div>`);
 }
 function reviewMarkup(){const r=room,me=r.host?'host':'guest';const errors=r.log.filter(entry=>!entry.answers[me]?.correct).length;const filter=r.reviewFilter||'wrong';const entries=r.log.map((entry,i)=>({...entry,index:i})).filter(entry=>filter==='all'||!entry.answers[me]?.correct);
  return `<section class="battle-review"><div class="battle-review-heading"><div><h2>本局回顧</h2><p>不計入課程錯題本。</p></div><div class="review-filter" role="group" aria-label="篩選作答紀錄"><button class="btn ${filter==='wrong'?'':'secondary'} small" data-action="duel-review-filter" data-filter="wrong" aria-pressed="${filter==='wrong'}">錯題 ${errors}</button><button class="btn ${filter==='all'?'':'secondary'} small" data-action="duel-review-filter" data-filter="all" aria-pressed="${filter==='all'}">全部 10 題</button></div></div>${!entries.length?`<div class="battle-review-empty">${icon('check')}<h3>這一局全部答對。</h3><p>可切換「全部 10 題」回看。</p></div>`:entries.map(entry=>{const q=E.Q.get(entry.qid),mine=entry.answers[me],choice=Number.isInteger(mine?.choice)?q.options[mine.choice]:'未作答（逾時）';return `<details class="battle-review-row" ${filter==='wrong'?'open':''}><summary><span>${String(entry.index+1).padStart(2,'0')}${entry.boss?' · 魔王':''}</span><strong>${esc(q.prompt)}</strong><b>${mine?.correct?'答對':'待複習'}</b></summary><div>${q.staff?A.staffView(q.staff):''}<p class="review-your-answer">你的答案：${esc(choice)}</p><p class="review-correct-answer">正確答案：<strong>${esc(q.options[q.correct])}</strong></p><h3>觀念解析</h3><p>${esc(q.explanation)}</p>${q.audio?A.audioCard({...q.audio,label:'重聽示範，對照正確答案。'},'duel',q.id):''}<p class="hint">課程：第 ${q.level} 級 ${esc(A.lesson(q.level).title)}</p></div></details>`;}).join('')}</section>`;
 }
 function resultView(){const r=room,me=r.host?'host':'guest',other=r.host?'guest':'host',tied=r.scores[me]===r.scores[other];A.setContent(`<div class="quiz-wrap"><button class="text-button" data-action="duel-leave">${icon('back')}返回對戰大廳</button><section class="result-hero"><div class="score-circle"><strong style="font-size:35px">${r.scores[me]}</strong><span>你的總分</span></div><div><h1>${tied?'這局平手，下次再分高下。':r.scores[me]>r.scores[other]?'這一局，你勝出了。':'好一場練習，再來一次。'}</h1><p>已完成第 ${r.matches} 局，對戰不影響課程晉級。</p><div class="result-actions">${r.host?'<button class="btn light" data-action="duel-rematch">再來一局</button>':'<span class="hint">等待房主邀請再來一局。</span>'}<button class="btn light" data-action="duel-leave">${r.mode==='ai'?'更換題庫或對手':'離開房間'}</button></div></div></section>${scoreBoard()}<div class="quiet-banner"><div><h3>本房間累計勝場</h3><p>${esc(r.host?r.name:r.otherName)} ${r.wins.host} 勝 / ${esc(r.host?r.otherName:r.name)} ${r.wins.guest} 勝。平手不計勝場。</p></div></div>${reviewMarkup()}</div>`);}
 function requestLeave(){const r=room;if(r&&['syncing','preview','playing','reveal'].includes(r.status)){A.confirmAction({title:'離開這場對戰？',message:'離開會結束本局，不計入課程成績。確認視窗開啟時，對戰時間仍會繼續。',confirmText:'返回對戰大廳',cancelText:'繼續對戰',onConfirm:()=>leave()});}else leave();}
 async function action(name,el){
  if(name.startsWith('duel-scope-')){
   const current=currentLevel();if(name==='duel-scope-all')selection=new Set(ALL);
   else if(name==='duel-scope-clear')selection.clear();
   else if(name==='duel-scope-current')selection=new Set([current]);
   else if(name==='duel-scope-chapter'){const start=Math.floor((current-1)/10)*10+1;selection=new Set(ALL.filter(n=>n>=start&&n<start+10));}
   else if(name==='duel-scope-add'){const from=Number($('#scope-from')?.value),to=Number($('#scope-to')?.value);if(!Number.isInteger(from)||!Number.isInteger(to)||from<1||to>100||from>to){A.notify('請輸入 1–100 的級數，結束級數不能小於起始級數。');return;}for(let n=from;n<=to;n++)selection.add(n);}
   savePrefs();syncScope();return;
  }
  if(name==='duel-ai'){startAi(el.dataset.profile);return;}if(name==='duel-create'){await start(true);return;}if(name==='duel-join'){await start(false);return;}if(name==='duel-leave'){requestLeave();return;}
  const r=room;if(!r)return;
  if(name==='duel-ready'&&!r.host&&r.otherId&&r.status==='waiting'&&!r.guestReady){r.guestReady=true;send('ready');r.notice='已準備，等待房主開始。';render();}
  else if(name==='duel-start')hostStart();
  else if(name==='duel-answer'&&r.status==='playing'&&el.dataset.round===r.round.roundId){const me=r.host?'host':'guest';if(r.answers[me])return;const elapsedMs=performance.now()-r.answerMono;if(elapsedMs<0||elapsedMs>=ROUND_MS){pulse();return;}const choice=Number(el.dataset.choice);if(!Number.isInteger(choice)||choice<0||choice>3)return;A.stopAudio();if(r.host)takeAnswer('host',choice);else{r.answers.guest={choice};send('answer',{...roundRef(),choice,elapsedMs});render();}}
  else if(name==='duel-review-filter'&&r.status==='result'){r.reviewFilter=el.dataset.filter==='all'?'all':'wrong';resultView();}
  else if(name==='duel-rematch'&&r.host&&r.status==='result'){r.status='waiting';r.guestReady=r.mode==='ai';r.notice='等待朋友準備下一局。';r.round=null;if(r.mode==='ai')hostStart();else{send('rematch');render();}}
  else if(name==='duel-copy'){try{await navigator.clipboard.writeText(r.code);A.notify('已複製房號 '+r.code+'。');}catch(_){A.notify('房號是 '+r.code+'，請選取後複製。');}}
 }
 document.addEventListener('change',e=>{const el=e.target;if(el.matches('[data-scope-chapter]')){const start=Number(el.dataset.scopeChapter)*10+1;for(let n=start;n<start+10;n++){if(el.checked)selection.add(n);else selection.delete(n);}savePrefs();syncScope();}else if(el.matches('[data-scope-level]')){if(el.checked)selection.add(Number(el.dataset.scopeLevel));else selection.delete(Number(el.dataset.scopeLevel));savePrefs();syncScope();}});
 document.addEventListener('input',e=>{if(e.target.id!=='scope-search')return;const term=e.target.value.trim().toLowerCase();document.querySelectorAll('[data-scope-label]').forEach(el=>{const l=A.lesson(el.dataset.scopeLabel);el.hidden=!!term&&!`${l.id} ${l.title} ${l.english} ${window.ArcoI18n?.t(l.title)||''}`.toLowerCase().includes(term);});});
 document.addEventListener('keydown',e=>{if(!room||room.status!=='playing'||e.repeat||e.ctrlKey||e.metaKey||e.altKey||document.querySelector('dialog[open]')||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||!(/^[1-4]$/).test(e.key))return;const choice=room.round.order[Number(e.key)-1],el=$(`[data-action="duel-answer"][data-choice="${choice}"]`);if(el&&!el.disabled){e.preventDefault();action('duel-answer',el);}});
 function leave(show=true){const r=room;if(r){send('leave');room=null;cleanupTimers(r);try{r.channel?.close();r.conn?.close();r.peer?.destroy();}catch(_){}A.stopAudio();}if(show){lastError='';lobby();}}
 function resetPreferences(){leave(false);preferredMode='internet';joinCode='';lastError='';selection=new Set(ALL);seen=[];}
 return {render,action,leave,requestLeave,resetPreferences,active:()=>!!room&&room.status!=='error',getRoom:()=>room,question:id=>E.Q.get(id),selection:()=>[...selection],pulse};
})();
if(location.hash==='#duel')window.ArcoDuel.render();